// Base
export { default as IOutlineCalendar2 } from '../assets/image/component/icon/base/outline-calendar-2.svg?react'
export { default as IOutlineArrowRight1 } from '../assets/image/component/icon/base/outline-arrow-right-1.svg?react'
export { default as IOutlineArrowRight3 } from '../assets/image/component/icon/base/outline-arrow-right-3.svg?react'
export { default as INext } from '../assets/image/component/icon/base/next.svg?react'
export { default as IRobot } from '../assets/image/component/icon/base/robot.svg?react'
export { default as IOutlineAward } from '../assets/image/component/icon/base/outline-award.svg?react'
export { default as IOutlinePeople } from '../assets/image/component/icon/base/outline-people.svg?react'
export { default as IOutlineProfile2user } from '../assets/image/component/icon/base/outline-profile-2user.svg?react'
export { default as IOutlineAdd } from '../assets/image/component/icon/base/outline-add.svg?react'
export { default as IOutlineUserTick } from '../assets/image/component/icon/base/outline-user-tick.svg?react'
export { default as IOutlineInfoCircle } from '../assets/image/component/icon/base/outline-info-circle.svg?react'
export { default as IOutlineTickCircle } from '../assets/image/component/icon/base/outline-tick-circle.svg?react'
export { default as IOutlineCloseCircle } from '../assets/image/component/icon/base/outline-close-circle.svg?react'
export { default as IOutlineWallet3 } from '../assets/image/component/icon/base/outline-wallet-3.svg?react'
export { default as IOutlineSearchNormal1 } from '../assets/image/component/icon/base/outline-search-normal-1.svg?react'
export { default as IClose } from '../assets/image/component/icon/base/close.svg?react'
export { default as ICheck } from '../assets/image/component/icon/base/check.svg?react'
export { default as IOutlineGrammerly } from '../assets/image/component/icon/base/outline-grammerly.svg?react'
export { default as IOutlineGift } from '../assets/image/component/icon/base/outline-gift.svg?react'
export { default as IOutlineExport2 } from '../assets/image/component/icon/base/outline-export-2.svg?react'
export { default as IOutlineExport3 } from '../assets/image/component/icon/base/outline-export-3.svg?react'
export { default as IQuestionCircle } from '../assets/image/component/icon/base/question-circle.svg?react'
// export { default as IOutlineUserAdd } from '../assets/image/component/icon/base/outline-user-add.svg?react'
export { default as IOutlineProfileAdd } from '../assets/image/component/icon/base/outline-profile-add.svg?react'
export { default as IOutlineLink } from '../assets/image/component/icon/base/outline-link.svg?react'
export { default as IOutlineWarning2 } from '../assets/image/component/icon/base/outline-warning-2.svg?react'
export { default as IOutlineShieldTick } from '../assets/image/component/icon/base/outline-shield-tick.svg?react'
export { default as IOutlineShieldSearch } from '../assets/image/component/icon/base/outline-shield-search.svg?react'
export { default as IOutlineFrame } from '../assets/image/component/icon/base/outline-frame.svg?react'
export { default as IRedemption } from '../assets/image/component/icon/base/redemption.svg?react'
export { default as IOutlineArrowUp1 } from '../assets/image/component/icon/base/outline-arrow-up-1.svg?react'
export { default as IOutlineClock } from '../assets/image/component/icon/base/outline-clock.svg?react'
export { default as IOutlineGlobal } from '../assets/image/component/icon/base/outline-global.svg?react'
export { default as IOutlineMenu } from '@/assets/image/component/icon/base/outline-menu.svg?react'
export { default as IOutlineMenu1 } from '@/assets/image/component/icon/base/outline-menu-1.svg?react'
export { default as IDocs } from '@/assets/image/component/icon/base/docs.svg?react'
export { default as IX } from '@/assets/image/component/icon/base/x.svg?react'
export { default as IOutlineMinus } from '@/assets/image/component/icon/base/outline-minus.svg?react'
export { default as IOutlineCopySuccess } from '@/assets/image/component/icon/base/outline-copy-success.svg?react'
export { default as IOutlineCopy } from '@/assets/image/component/icon/base/outline-copy.svg?react'
export { default as IOutlineTimer1 } from '@/assets/image/component/icon/base/outline-timer-1.svg?react'
export { default as IOutlineDocumentText1 } from '@/assets/image/component/icon/base/outline-document-text-1.svg?react'
export { default as IPost } from '@/assets/image/component/icon/base/post.svg?react'
export { default as IReload } from '@/assets/image/component/icon/base/reload.svg?react'
export { default as IInfoCircle } from '@/assets/image/component/icon/base/info-circle.svg?react'
export { default as ITelegram } from '../assets/image/component/icon/base/telegram.svg?react'
export { default as IOutlineChrome } from '../assets/image/component/icon/base/outline-chrome.svg?react'
export { default as IOutlineSetting } from '../assets/image/component/icon/base/outline-setting.svg?react'
export { default as IOutlineProfileTick } from '../assets/image/component/icon/base/outline-profile-tick.svg?react'
export { default as ILoading } from '../assets/image/component/icon/base/loading.svg?react'
export { default as IOutlineProfileRemove } from '../assets/image/component/icon/base/outline-profile-remove.svg?react'
export { default as IRankingList } from '../assets/image/component/icon/base/ranking-list.svg?react'
export { default as IOutlineNotificationBing } from '../assets/image/component/icon/base/outline-notification-bing.svg?react'
export { default as IOutlineHeart } from '../assets/image/component/icon/base/outline-heart.svg?react'
export { default as IOutlineHome2 } from '../assets/image/component/icon/base/outline-home-2.svg?react'
export { default as IOutlineRanking } from '../assets/image/component/icon/base/outline-ranking.svg?react'
export { default as IOutlineLogin } from '../assets/image/component/icon/base/outline-login.svg?react'
export { default as IOutlineLogout } from '../assets/image/component/icon/base/outline-logout.svg?react'
export { default as IOutlineCrown } from '../assets/image/component/icon/base/outline-crown.svg?react'
export { default as IOutlineUserOctagon } from '../assets/image/component/icon/base/outline-user-octagon.svg?react'
export { default as IOutlineMoreSquare } from '../assets/image/component/icon/base/outline-more-square.svg?react'
export { default as IOutlineHeartRemove } from '../assets/image/component/icon/base/outline-heart-remove.svg?react'
export { default as IOutlineMonitor } from '../assets/image/component/icon/base/outline-monitor.svg?react'
export { default as IOutlineShare } from '../assets/image/component/icon/base/outline-share.svg?react'
export { default as IOutlineTrash } from '../assets/image/component/icon/base/outline-trash.svg?react'
export { default as IOutlineEdit } from '../assets/image/component/icon/base/outline-edit.svg?react'
export { default as IOutlineEdit2 } from '../assets/image/component/icon/base/outline-edit-2.svg?react'
export { default as IOutlineSort } from '../assets/image/component/icon/base/outline-sort.svg?react'
export { default as IOutlineMedal } from '../assets/image/component/icon/base/outline-medal.svg?react'
export { default as ICyclical } from '../assets/image/component/icon/base/cyclical.svg?react'
export { default as IOutlineExport1 } from '../assets/image/component/icon/base/outline-export-1.svg?react'
export { default as IOutlineImport1 } from '../assets/image/component/icon/base/outline-import-1.svg?react'
export { default as IOutlineEyeSlash } from '../assets/image/component/icon/base/outline-eye-slash.svg?react'
export { default as IOutlineEye } from '../assets/image/component/icon/base/outline-eye.svg?react'
export { default as IOutlineChart2 } from '../assets/image/component/icon/base/outline-chart-2.svg?react'
export { default as IShare } from '../assets/image/component/icon/base/share.svg?react'
export { default as IShort } from '../assets/image/component/icon/base/short.svg?react'
export { default as ILong } from '../assets/image/component/icon/base/long.svg?react'
export { default as IRefresh } from '../assets/image/component/icon/base/refresh.svg?react'
export { default as IOutlineNotification } from '../assets/image/component/icon/base/outline-notification.svg?react'
export { default as IOutlineCloseNotification } from '../assets/image/component/icon/base/outline-close-notification.svg?react'
export { default as IOutlineFilter } from '../assets/image/component/icon/base/outline-filter.svg?react'
export { default as IOutlineFilterRemove } from '../assets/image/component/icon/base/outline-filter-remove.svg?react'
export { default as IFilter } from '../assets/image/component/icon/base/filter.svg?react'
export { default as IFilterFill } from '../assets/image/component/icon/base/filter-fill.svg?react'
export { default as IOutlineFlash } from '../assets/image/component/icon/base/outline-flash.svg?react'

// colorful
export { default as IGoogle } from '../assets/image/component/icon/colorful/google.svg?react'
export { default as ITwitterscan } from '../assets/image/component/icon/colorful/twitterscan.svg?react'

// ViewPlugin
export { default as IMCChart } from '../assets/image/component/icon/multicolor/chart.svg?react'
export { default as IMCScale } from '../assets/image/component/icon/multicolor/scale.svg?react'
export { default as IMCUsers } from '../assets/image/component/icon/multicolor/users.svg?react'
export { default as IMCScreen } from '../assets/image/component/icon/multicolor/screen.svg?react'




